name: ClearPlayerInv
main: Artsakhskiyy\ClearPlayerInv\Main
version: 1.0.2
api: 5.0.0
commands:
  clearinv:
    description: Clear your own inventory...
    usage: "/clearinv"
    permission: clearplayerinv.command.clearinv
  clearplayer:
    description: Clear another player's inventory...
    usage: "/clearplayer <nickname>"
    permission: clearplayerinv.command.clearplayer

permissions:
  clearplayerinv.command.clearinv:
    description: Allows player to clear own inventory...
    default: op
  clearplayerinv.command.clearplayer:
    description: Allows player to clear another player's inventory...
    default: op
