name: ClearPlayer
main: Artsakhskiyy\ClearPlayer\Main
version: 1.0.1
api: 5.0.0
commands:
  clearinv:
    description: Clear your own inventory...
    usage: "/clearinv"
    permission: clearplayer.command.clearinv
  clearplayer:
    description: Clear another player's inventory...
    usage: "/clearplayer <nickname>"
    permission: clearplayer.command.clearplayer

permissions:
  clearplayer.command.clearinv:
    description: Allows player to clear own inventory...
    default: op
  clearplayer.command.clearplayer:
    description: Allows player to clear another player's inventory...
    default: op
